/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119111-gca48e7bb70-20250402"
#endif /* AVUTIL_FFVERSION_H */
